version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: turkmenfinder
      POSTGRES_PASSWORD: turkmenfinder
      POSTGRES_DB: turkmenfinder
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: